/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as DoshasRouteImport } from './routes/doshas'
import { Route as HoroscopesRouteImport } from './routes/horoscopes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MuhuratRouteImport } from './routes/muhurat'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AstrologersSlugRouteImport } from './routes/astrologers/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const DoshasRoute = DoshasRouteImport.update({
  id: '/doshas',
  path: '/doshas',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopesRoute = HoroscopesRouteImport.update({
  id: '/horoscopes',
  path: '/horoscopes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MuhuratRoute = MuhuratRouteImport.update({
  id: '/muhurat',
  path: '/muhurat',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologersSlugRoute = AstrologersSlugRouteImport.update({
  id: '/astrologers/$slug',
  path: '/astrologers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/consultation': typeof ConsultationRoute
  '/doshas': typeof DoshasRoute
  '/horoscopes': typeof HoroscopesRoute
  '/login': typeof LoginRoute
  '/muhurat': typeof MuhuratRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/astrologers/$slug': typeof AstrologersSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/consultation': typeof ConsultationRoute
  '/doshas': typeof DoshasRoute
  '/horoscopes': typeof HoroscopesRoute
  '/login': typeof LoginRoute
  '/muhurat': typeof MuhuratRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/astrologers/$slug': typeof AstrologersSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/consultation': typeof ConsultationRoute
  '/doshas': typeof DoshasRoute
  '/horoscopes': typeof HoroscopesRoute
  '/login': typeof LoginRoute
  '/muhurat': typeof MuhuratRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/astrologers/$slug': typeof AstrologersSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/consultation'
    | '/doshas'
    | '/horoscopes'
    | '/login'
    | '/muhurat'
    | '/shop'
    | '/signup'
    | '/astrologers/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/consultation'
    | '/doshas'
    | '/horoscopes'
    | '/login'
    | '/muhurat'
    | '/shop'
    | '/signup'
    | '/astrologers/$slug'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/consultation'
    | '/doshas'
    | '/horoscopes'
    | '/login'
    | '/muhurat'
    | '/shop'
    | '/signup'
    | '/astrologers/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ConsultationRoute: typeof ConsultationRoute
  DoshasRoute: typeof DoshasRoute
  HoroscopesRoute: typeof HoroscopesRoute
  LoginRoute: typeof LoginRoute
  MuhuratRoute: typeof MuhuratRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  AstrologersSlugRoute: typeof AstrologersSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doshas': {
      id: '/doshas'
      path: '/doshas'
      fullPath: '/doshas'
      preLoaderRoute: typeof DoshasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscopes': {
      id: '/horoscopes'
      path: '/horoscopes'
      fullPath: '/horoscopes'
      preLoaderRoute: typeof HoroscopesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muhurat': {
      id: '/muhurat'
      path: '/muhurat'
      fullPath: '/muhurat'
      preLoaderRoute: typeof MuhuratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrologers/$slug': {
      id: '/astrologers/$slug'
      path: '/astrologers/$slug'
      fullPath: '/astrologers/$slug'
      preLoaderRoute: typeof AstrologersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ConsultationRoute: ConsultationRoute,
  DoshasRoute: DoshasRoute,
  HoroscopesRoute: HoroscopesRoute,
  LoginRoute: LoginRoute,
  MuhuratRoute: MuhuratRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  AstrologersSlugRoute: AstrologersSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
